# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LC_aCriJoPhe0CYZmCLL2NR0sJYR3WO
"""



import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("delivery_data.csv")

print("Dataset Shape:", df.shape)
df.head()

df.columns = df.columns.str.strip().str.lower()

print("Columns:")
print(df.columns.tolist())

required_cols = [
    "data",
    "route_type",
    "trip_uuid",
    "source_center",
    "source_name",
    "destination_center",
    "destination_name",
    "actual_time",
    "osrm_time",
    "osrm_distance",
    "actual_distance_to_destination",
    "segment_actual_time",
    "segment_osrm_time",
    "segment_osrm_distance"
]

available_cols = [col for col in required_cols if col in df.columns]

data = df[available_cols].copy()

print("Available Columns Used:")
print(available_cols)

data.head()

data = data.drop_duplicates()
data = data.dropna()

for col in ["actual_time", "osrm_time"]:
    data = data[data[col] > 0]

print("Cleaned Data Shape:", data.shape)
data.head()

data["delay"] = data["actual_time"] - data["osrm_time"]

data["delay_ratio"] = data["actual_time"] / data["osrm_time"]

data["sla_breach"] = np.where(data["delay_ratio"] > 1.20, 1, 0)

data["within_15_percent_osrm"] = np.where(
    abs(data["actual_time"] - data["osrm_time"]) <= 0.15 * data["actual_time"],
    1,
    0
)

data.head()



edge_data = data.groupby(
    ["source_name", "destination_name", "route_type"]
).agg(
    median_delay_ratio=("delay_ratio", "median"),
    avg_delay_ratio=("delay_ratio", "mean"),
    total_delay=("delay", "sum"),
    avg_actual_time=("actual_time", "mean"),
    avg_osrm_time=("osrm_time", "mean"),
    trip_count=("trip_uuid", "nunique"),
    sla_breach_count=("sla_breach", "sum")
).reset_index()

edge_data.head()

G = nx.DiGraph()

for _, row in edge_data.iterrows():
    G.add_edge(
        row["source_name"],
        row["destination_name"],
        weight=row["median_delay_ratio"],
        route_type=row["route_type"],
        avg_delay_ratio=row["avg_delay_ratio"],
        total_delay=row["total_delay"],
        trip_count=row["trip_count"],
        sla_breach_count=row["sla_breach_count"]
    )

print("Number of hubs/nodes:", G.number_of_nodes())
print("Number of corridors/edges:", G.number_of_edges())

plt.figure(figsize=(14, 10))

pos = nx.spring_layout(G, seed=42, k=0.3)

nx.draw_networkx_nodes(G, pos, node_size=40)
nx.draw_networkx_edges(G, pos, alpha=0.25, arrows=True)

plt.title("Delhivery Logistics Network Graph")
plt.axis("off")
plt.show()

degree_centrality = nx.degree_centrality(G)
betweenness_centrality = nx.betweenness_centrality(G, weight="weight")
in_degree = dict(G.in_degree())
out_degree = dict(G.out_degree())
clustering = nx.clustering(G.to_undirected())

hub_df = pd.DataFrame({
    "hub": list(G.nodes()),
    "degree_centrality": [degree_centrality.get(h, 0) for h in G.nodes()],
    "betweenness_centrality": [betweenness_centrality.get(h, 0) for h in G.nodes()],
    "in_degree": [in_degree.get(h, 0) for h in G.nodes()],
    "out_degree": [out_degree.get(h, 0) for h in G.nodes()],
    "clustering_coefficient": [clustering.get(h, 0) for h in G.nodes()]
})

hub_df.head()

# Recreate hub_df cleanly from graph metrics only

hub_df = pd.DataFrame({
    "hub": list(G.nodes()),
    "degree_centrality": [degree_centrality.get(h, 0) for h in G.nodes()],
    "betweenness_centrality": [betweenness_centrality.get(h, 0) for h in G.nodes()],
    "in_degree": [in_degree.get(h, 0) for h in G.nodes()],
    "out_degree": [out_degree.get(h, 0) for h in G.nodes()],
    "clustering_coefficient": [clustering.get(h, 0) for h in G.nodes()]
})

from sklearn.preprocessing import MinMaxScaler



source_delay = data.groupby("source_name")["delay"].sum().reset_index()
source_delay.columns = ["hub", "source_delay"]

destination_delay = data.groupby("destination_name")["delay"].sum().reset_index()
destination_delay.columns = ["hub", "destination_delay"]

source_sla = data.groupby("source_name")["sla_breach"].sum().reset_index()
source_sla.columns = ["hub", "source_sla_breaches"]

destination_sla = data.groupby("destination_name")["sla_breach"].sum().reset_index()
destination_sla.columns = ["hub", "destination_sla_breaches"]

hub_df = hub_df.merge(source_delay, on="hub", how="left")
hub_df = hub_df.merge(destination_delay, on="hub", how="left")
hub_df = hub_df.merge(source_sla, on="hub", how="left")
hub_df = hub_df.merge(destination_sla, on="hub", how="left")

hub_df.fillna(0, inplace=True)

hub_df["total_delay_contribution"] = (
    hub_df["source_delay"] + hub_df["destination_delay"]
)

hub_df["total_sla_breaches"] = (
    hub_df["source_sla_breaches"] + hub_df["destination_sla_breaches"]
)

# Normalize values between 0 and 1
scaler = MinMaxScaler()

score_features = [
    "betweenness_centrality",
    "degree_centrality",
    "total_delay_contribution",
    "total_sla_breaches"
]

normalized_values = scaler.fit_transform(hub_df[score_features])

hub_df[[
    "norm_betweenness",
    "norm_degree",
    "norm_delay",
    "norm_sla"
]] = normalized_values

# Final weighted bottleneck score
hub_df["bottleneck_score"] = (
    0.35 * hub_df["norm_betweenness"] +
    0.25 * hub_df["norm_degree"] +
    0.25 * hub_df["norm_delay"] +
    0.15 * hub_df["norm_sla"]
)

top_5_hubs = hub_df.sort_values(
    "bottleneck_score", ascending=False
).head(5)

top_5_hubs

plt.figure(figsize=(10, 5))

plt.barh(top_5_hubs["hub"], top_5_hubs["bottleneck_score"])

plt.xlabel("Improved Bottleneck Score")
plt.ylabel("Hub")
plt.title("Top 5 Bottleneck Hubs")
plt.gca().invert_yaxis()
plt.show()

delayed_corridors = edge_data[edge_data["median_delay_ratio"] > 1.20]
delayed_corridors = delayed_corridors.sort_values("total_delay", ascending=False)

delayed_corridors.head(10)

top_corridors = delayed_corridors.head(10).copy()

top_corridors["corridor"] = (
    top_corridors["source_name"] + " → " + top_corridors["destination_name"]
)

plt.figure(figsize=(12, 6))

plt.barh(top_corridors["corridor"], top_corridors["median_delay_ratio"])

plt.xlabel("Median Delay Ratio")
plt.ylabel("Corridor")
plt.title("Top 10 Delayed Corridors")
plt.gca().invert_yaxis()
plt.show()

ml_data = data.copy()

le_route = LabelEncoder()
le_source = LabelEncoder()
le_destination = LabelEncoder()

ml_data["route_type_encoded"] = le_route.fit_transform(ml_data["route_type"].astype(str))
ml_data["source_encoded"] = le_source.fit_transform(ml_data["source_name"].astype(str))
ml_data["destination_encoded"] = le_destination.fit_transform(ml_data["destination_name"].astype(str))

ml_data.head()

baseline_features = [
    "route_type_encoded",
    "source_encoded",
    "destination_encoded",
    "osrm_time"
]

if "osrm_distance" in ml_data.columns:
    baseline_features.append("osrm_distance")

if "actual_distance_to_destination" in ml_data.columns:
    baseline_features.append("actual_distance_to_destination")

X_base = ml_data[baseline_features]
y = ml_data["actual_time"]

X_train_base, X_test_base, y_train, y_test = train_test_split(
    X_base, y, test_size=0.2, random_state=42
)

baseline_model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.08,
    max_depth=6,
    random_state=42
)

baseline_model.fit(X_train_base, y_train)

baseline_pred = baseline_model.predict(X_test_base)

baseline_mae = mean_absolute_error(y_test, baseline_pred)

baseline_15_accuracy = np.mean(
    abs(y_test - baseline_pred) <= 0.15 * y_test
)

print("Baseline MAE:", baseline_mae)
print("Baseline 15% Accuracy:", baseline_15_accuracy)

source_graph = hub_df.copy()
source_graph.columns = [
    "source_name" if c == "hub" else "source_" + c
    for c in source_graph.columns
]

destination_graph = hub_df.copy()
destination_graph.columns = [
    "destination_name" if c == "hub" else "destination_" + c
    for c in destination_graph.columns
]

graph_ml = ml_data.merge(source_graph, on="source_name", how="left")
graph_ml = graph_ml.merge(destination_graph, on="destination_name", how="left")

graph_ml.fillna(0, inplace=True)

graph_ml.head()

graph_features = baseline_features + [
    "source_degree_centrality",
    "source_betweenness_centrality",
    "source_in_degree",
    "source_out_degree",
    "source_clustering_coefficient",
    "source_total_delay_contribution",
    "source_total_sla_breaches",
    "source_bottleneck_score",

    "destination_degree_centrality",
    "destination_betweenness_centrality",
    "destination_in_degree",
    "destination_out_degree",
    "destination_clustering_coefficient",
    "destination_total_delay_contribution",
    "destination_total_sla_breaches",
    "destination_bottleneck_score"
]

X_graph = graph_ml[graph_features]
y_graph = graph_ml["actual_time"]

X_train_graph, X_test_graph, y_train_graph, y_test_graph = train_test_split(
    X_graph, y_graph, test_size=0.2, random_state=42
)

graph_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.06,
    max_depth=7,
    random_state=42
)

graph_model.fit(X_train_graph, y_train_graph)

graph_pred = graph_model.predict(X_test_graph)

graph_mae = mean_absolute_error(y_test_graph, graph_pred)

graph_15_accuracy = np.mean(
    abs(y_test_graph - graph_pred) <= 0.15 * y_test_graph
)

print("Graph-Enhanced MAE:", graph_mae)
print("Graph-Enhanced 15% Accuracy:", graph_15_accuracy)

osrm_mae = mean_absolute_error(data["actual_time"], data["osrm_time"])

osrm_15_accuracy = data["within_15_percent_osrm"].mean()

comparison = pd.DataFrame({
    "Model": [
        "OSRM Current Estimate",
        "Baseline ML Model",
        "Graph-Enhanced ML Model"
    ],
    "MAE": [
        osrm_mae,
        baseline_mae,
        graph_mae
    ],
    "15% Accuracy": [
        osrm_15_accuracy,
        baseline_15_accuracy,
        graph_15_accuracy
    ]
})

comparison

plt.figure(figsize=(9, 5))

plt.bar(comparison["Model"], comparison["MAE"])

plt.ylabel("Mean Absolute Error")
plt.title("Model Comparison by MAE")
plt.xticks(rotation=20)
plt.show()

plt.figure(figsize=(9, 5))

plt.bar(comparison["Model"], comparison["15% Accuracy"])

plt.ylabel("15% Accuracy")
plt.title("Model Comparison by 15% Accuracy")
plt.xticks(rotation=20)
plt.show()

route_type_analysis = data.groupby("route_type").agg(
    avg_actual_time=("actual_time", "mean"),
    avg_osrm_time=("osrm_time", "mean"),
    avg_delay=("delay", "mean"),
    avg_delay_ratio=("delay_ratio", "mean"),
    sla_breach_rate=("sla_breach", "mean"),
    total_trips=("trip_uuid", "nunique")
).reset_index()

route_type_analysis

len(graph_ml)

print(graph_ml.shape)

source_threshold = graph_ml["source_bottleneck_score"].quantile(0.75)
destination_threshold = graph_ml["destination_bottleneck_score"].quantile(0.75)
time_threshold = graph_ml["osrm_time"].quantile(0.75)

graph_ml["route_risk_score"] = (
    (graph_ml["source_bottleneck_score"] > source_threshold).astype(int) +
    (graph_ml["destination_bottleneck_score"] > destination_threshold).astype(int) +
    (graph_ml["osrm_time"] > time_threshold).astype(int)
)

if "osrm_distance" in graph_ml.columns:
    distance_threshold = graph_ml["osrm_distance"].quantile(0.75)
    graph_ml["route_risk_score"] += (
        graph_ml["osrm_distance"] > distance_threshold
    ).astype(int)

graph_ml["recommended_route_type"] = np.where(
    graph_ml["route_risk_score"] >= 2,
    "FTL",
    "Carting"
)

graph_ml[[
    "source_name",
    "destination_name",
    "route_type",
    "recommended_route_type",
    "route_risk_score",
    "source_bottleneck_score",
    "destination_bottleneck_score",
    "osrm_time"
]].head(10)

recommendation_summary = graph_ml.groupby(
    ["route_type", "recommended_route_type"]
).size().reset_index(name="count")

recommendation_summary

REVENUE_LOSS_PER_LATE_DELIVERY = 100

hub_impact = data.groupby("source_name").agg(
    total_trips=("trip_uuid", "nunique"),
    sla_breaches=("sla_breach", "sum"),
    total_delay=("delay", "sum")
).reset_index()

hub_impact["sla_breach_rate"] = hub_impact["sla_breaches"] / hub_impact["total_trips"]

hub_impact["revenue_at_risk"] = (
    hub_impact["sla_breaches"] * REVENUE_LOSS_PER_LATE_DELIVERY
)

hub_impact = hub_impact.sort_values("revenue_at_risk", ascending=False)

top_5_revenue_hubs = hub_impact.head(5)

top_5_revenue_hubs

top_3_hubs = top_5_revenue_hubs.head(3)

ASSUMED_IMPROVEMENT = 0.25

late_deliveries_reduced = top_3_hubs["sla_breaches"].sum() * ASSUMED_IMPROVEMENT

revenue_recovered = late_deliveries_reduced * REVENUE_LOSS_PER_LATE_DELIVERY

print("Estimated Late Deliveries Reduced:", late_deliveries_reduced)
print("Estimated Revenue Recovered:", revenue_recovered)

memo = f"""
NETWORK OPERATIONS STRATEGY MEMO

Project Title:
Optimizing Delivery ETAs with Graph-Based Network Intelligence

1. Executive Summary

The logistics network was modeled as a directed weighted graph where each facility acts as a node and each movement corridor acts as an edge. The edge weight was calculated using the median delay ratio between actual delivery time and OSRM-estimated delivery time.

This graph-based approach helps identify bottleneck hubs, delayed corridors, and structurally risky parts of the logistics network. It also improves ETA prediction by adding graph-level intelligence to the machine learning model.

2. Model Performance

OSRM Current Estimate:
MAE = {osrm_mae:.2f}
15% Accuracy = {osrm_15_accuracy:.2%}

Baseline Machine Learning Model:
MAE = {baseline_mae:.2f}
15% Accuracy = {baseline_15_accuracy:.2%}

Graph-Enhanced Machine Learning Model:
MAE = {graph_mae:.2f}
15% Accuracy = {graph_15_accuracy:.2%}

3. Top 5 Bottleneck Hubs

{top_5_hubs[['hub', 'bottleneck_score', 'total_delay_contribution', 'total_sla_breaches']].to_string(index=False)}

4. Key Operational Findings

- Hubs with high betweenness centrality act as chokepoints because many routes pass through them.
- Corridors with delay ratio above 1.20 are chronic delay corridors.
- Graph-based features improve ETA prediction because they capture network risk.
- High-risk corridors should be reviewed for FTL movement instead of Carting.
- Bottleneck hubs contribute disproportionately to SLA breaches and revenue-at-risk.

5. Recommendations

Recommendation 1:
Upgrade processing capacity at the top 3 bottleneck hubs.

Recommendation 2:
Prioritize delayed corridors where actual time exceeds OSRM time by more than 20%.

Recommendation 3:
Use bottleneck score as a weekly operational monitoring metric.

Recommendation 4:
Shift high-risk long-distance corridors from Carting to FTL where delay risk is high.

Recommendation 5:
Use the graph-enhanced ETA model instead of relying only on OSRM estimates.

6. Estimated Business Impact

Assuming a 25% improvement in the top 3 bottleneck hubs:

Estimated late deliveries reduced:
{late_deliveries_reduced:.0f}

Estimated revenue recovered:
₹{revenue_recovered:.2f}

7. Conclusion

The graph-based intelligence system provides better visibility into delivery delays than OSRM alone. It identifies bottleneck hubs, highlights delayed corridors, improves ETA prediction, and supports data-backed FTL versus Carting decisions.
"""
print(memo)
output_folder = "graph_project_outputs"

os.makedirs(output_folder, exist_ok=True)

with open(f"{output_folder}/network_operations_strategy_memo.txt", "w", encoding="utf-8") as f:
     f.write(memo)

hub_df.to_csv(f"{output_folder}/hub_bottleneck_scores.csv", index=False, encoding="utf-8")
edge_data.to_csv(f"{output_folder}/graph_corridor_data.csv", index=False, encoding="utf-8")

delayed_corridors.to_csv(f"{output_folder}/delayed_corridors.csv", index=False, encoding="utf-8")

comparison.to_csv(f"{output_folder}/model_performance_comparison.csv", index=False, encoding="utf-8")

route_type_analysis.to_csv(f"{output_folder}/ftl_vs_carting_analysis.csv", index=False, encoding="utf-8")

recommendation_summary.to_csv(f"{output_folder}/route_type_recommendation_summary.csv", index=False, encoding="utf-8")

top_5_hubs.to_csv(f"{output_folder}/top_5_bottleneck_hubs.csv", index=False, encoding="utf-8")

top_5_revenue_hubs.to_csv(f"{output_folder}/top_5_revenue_hubs.csv", index=False, encoding="utf-8")



print(f"All output files saved inside folder: {output_folder}")






























